### ISSUE TITLE
Questions: How long doe the batteries last

### ISSUE THREAD

**Issue by maccoylton** [TobiasNiggemeyer/ESP8266HomekitThermostat#1]
I'm curious as to how long the batteries last?

**Comment by TobiasNiggemeyer** [comment]
The "addon" is currently powered by a 5V DC Adapter (see README section open points). In my case this is a suitable solution, but it would be nice to add a battery to the system (maybe i have to change the mainboard, since the esp8266-01 draws alot of current)
